module.exports = {
  extends: ["eslint:recommended", "plugin:prettier/recommended"],
  parserOptions: {
    ecmaVersion: 6,
    sourceType: "module",
  },
  env: {
    browser: true,
    jest: true,
    node: true,
  },
  rules: {
    // possible errors
    "prefer-const": "error",
    "no-console": "error",
    "no-var": "error",
    // best practices
    "consistent-return": "error",
    curly: "error",
    "default-case": "error",
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    eqeqeq: ["error", "always"],
    "guard-for-in": "error",
    "no-else-return": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-floating-decimal": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-multi-str": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-unused-expressions": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-return": "error",
    "prefer-promise-reject-errors": "error",
    radix: "error",
    "require-await": "error",
    "wrap-iife": ["error", "outside"],
    yoda: "error",
    // variables
    "no-undefined": "error",
    "no-use-before-define": "error",
    // ES6
    "arrow-parens": ["error", "always"],
    "no-confusing-arrow": "error",
    "no-duplicate-imports": "error",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "object-shorthand": ["error", "always"],
    "prefer-arrow-callback": "error",
    "prefer-destructuring": [
      "error",
      {
        array: true,
        object: true,
      },
      {
        enforceForRenamedProperties: false,
      },
    ],
    "prefer-spread": "error",
    "prefer-template": "error",
    "sort-imports": "error",
  },
};
