name: lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: install
      run: npm run install

    - name: lint
      run: npm run lint
